# Academic Website Builder
# https://sourcethemes.com/academic/
#
# The presence of this file is for compatibility with Blogdown and Forestry.
# If you are not using those tools, this file may be deleted.
#
# The actual configuration files are stored in the `config/_default/` folder.
# theme = ["hugo-embed-pdf-shortcode", "Academic"]
[security]
  enableInlineShortcodes = true

[params]
  header = """
    <a class="navbar-brand" href="/" title="InSeco">
      <img src="/images/inseco.png" alt="InSeco Logo" width="100">
    </a>
  """
